package vislabExample.model.db;

// Generated 15.05.2011 14:44:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private String label;
	private Set products = new HashSet(0);

	public Category() {
	}

	public Category(String label) {
		this.label = label;
	}

	public Category(String label, Set products) {
		this.label = label;
		this.products = products;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
